/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ierc1155TokenReceiverSol from "./IERC1155TokenReceiver.sol";
export type { ierc1155TokenReceiverSol };
export type { IERC1155 } from "./IERC1155";
export type { IERC1155MetadataURI } from "./IERC1155MetadataURI";
export type { IERC1155Receiver } from "./IERC1155Receiver";
export type { IERC1155Transfer } from "./IERC1155Transfer";
