/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockEcosystemContractSol from "./MockEcosystemContract.sol";
export type { mockEcosystemContractSol };
import type * as mockTIcketTokenSol from "./MockTIcketToken.sol";
export type { mockTIcketTokenSol };
export type { MockPaymentTokenWithIOwner } from "./MockPaymentTokenWithIOwner";
