/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc1155Sol from "./ERC1155.sol";
export * as erc1155ReceiverSol from "./ERC1155Receiver.sol";
export * as interfaces from "./interfaces";
export * as internals from "./internals";
export { ERC1155Transfer__factory } from "./ERC1155Transfer__factory";
