/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace IDiamondCut {
  export type FacetCutStruct = {
    facetAddress: PromiseOrValue<string>;
    action: PromiseOrValue<BigNumberish>;
    functionSelectors: PromiseOrValue<BytesLike>[];
  };

  export type FacetCutStructOutput = [string, number, string[]] & {
    facetAddress: string;
    action: number;
    functionSelectors: string[];
  };
}

export interface DiamondDeployInterface extends utils.Interface {
  functions: {
    "deploy(address,uint256,bytes,(address,uint8,bytes4[])[])": FunctionFragment;
    "registryAddress()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "deploy" | "registryAddress"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "deploy",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      IDiamondCut.FacetCutStruct[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "registryAddress",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "deploy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registryAddress",
    data: BytesLike
  ): Result;

  events: {};
}

export interface DiamondDeploy extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DiamondDeployInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    deploy(
      owner: PromiseOrValue<string>,
      _salt: PromiseOrValue<BigNumberish>,
      _bytecode: PromiseOrValue<BytesLike>,
      _facetCuts: IDiamondCut.FacetCutStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    registryAddress(overrides?: CallOverrides): Promise<[string]>;
  };

  deploy(
    owner: PromiseOrValue<string>,
    _salt: PromiseOrValue<BigNumberish>,
    _bytecode: PromiseOrValue<BytesLike>,
    _facetCuts: IDiamondCut.FacetCutStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  registryAddress(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    deploy(
      owner: PromiseOrValue<string>,
      _salt: PromiseOrValue<BigNumberish>,
      _bytecode: PromiseOrValue<BytesLike>,
      _facetCuts: IDiamondCut.FacetCutStruct[],
      overrides?: CallOverrides
    ): Promise<string>;

    registryAddress(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    deploy(
      owner: PromiseOrValue<string>,
      _salt: PromiseOrValue<BigNumberish>,
      _bytecode: PromiseOrValue<BytesLike>,
      _facetCuts: IDiamondCut.FacetCutStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    registryAddress(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    deploy(
      owner: PromiseOrValue<string>,
      _salt: PromiseOrValue<BigNumberish>,
      _bytecode: PromiseOrValue<BytesLike>,
      _facetCuts: IDiamondCut.FacetCutStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    registryAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
