/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20Sol from "./ERC20.sol";
export type { erc20Sol };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as libraries from "./libraries";
export type { libraries };
