/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface ModeratorInterface extends utils.Interface {
  functions: {
    "getModeratorRank(address)": FunctionFragment;
    "setModeratorRank(address,uint8)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "getModeratorRank" | "setModeratorRank"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getModeratorRank",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setModeratorRank",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "getModeratorRank",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setModeratorRank",
    data: BytesLike
  ): Result;

  events: {};
}

export interface Moderator extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ModeratorInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getModeratorRank(
      _moderator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[number] & { moderatorRank_: number }>;

    setModeratorRank(
      _moderator: PromiseOrValue<string>,
      _rank: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  getModeratorRank(
    _moderator: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<number>;

  setModeratorRank(
    _moderator: PromiseOrValue<string>,
    _rank: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getModeratorRank(
      _moderator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<number>;

    setModeratorRank(
      _moderator: PromiseOrValue<string>,
      _rank: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getModeratorRank(
      _moderator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setModeratorRank(
      _moderator: PromiseOrValue<string>,
      _rank: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getModeratorRank(
      _moderator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setModeratorRank(
      _moderator: PromiseOrValue<string>,
      _rank: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
