/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../../common";
import type {
  LibERC20,
  LibERC20Interface,
} from "../../../../../facets/Tokens/ERC20/libraries/LibERC20";

const _abi = [
  {
    inputs: [],
    name: "PRIMARY_CURRENCY_ID",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60bd610052600b82828239805160001a607314610045577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c8063b7dfc1ca146038575b600080fd5b603e6052565b60405160499190606e565b60405180910390f35b600081565b6000819050919050565b6068816057565b82525050565b6000602082019050608160008301846061565b9291505056fea26469706673582212200badcfb9ad22c82243d303749720c24027ca2a69b1c4d7765b2ac3d26d5fbd3064736f6c63430008090033";

type LibERC20ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: LibERC20ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class LibERC20__factory extends ContractFactory {
  constructor(...args: LibERC20ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<LibERC20> {
    return super.deploy(overrides || {}) as Promise<LibERC20>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): LibERC20 {
    return super.attach(address) as LibERC20;
  }
  override connect(signer: Signer): LibERC20__factory {
    return super.connect(signer) as LibERC20__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LibERC20Interface {
    return new utils.Interface(_abi) as LibERC20Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LibERC20 {
    return new Contract(address, _abi, signerOrProvider) as LibERC20;
  }
}
