/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as diamondDeploySol from "./diamondDeploy.sol";
export { IDiamondDeploy__factory } from "./IDiamondDeploy__factory";
