/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace LibMemberLevel {
  export type LeafStruct = {
    memberAddress: PromiseOrValue<string>;
    level: PromiseOrValue<BigNumberish>;
    timestamp: PromiseOrValue<BigNumberish>;
  };

  export type LeafStructOutput = [string, number, number] & {
    memberAddress: string;
    level: number;
    timestamp: number;
  };
}

export declare namespace TicketCreate {
  export type TicketMetaStruct = {
    title: PromiseOrValue<string>;
    description: PromiseOrValue<string>;
    imageHash: PromiseOrValue<string>;
  };

  export type TicketMetaStructOutput = [string, string, string] & {
    title: string;
    description: string;
    imageHash: string;
  };
}

export declare namespace LibERC1155TransferConstraints {
  export type TransferLimitStruct = {
    maxTransfers: PromiseOrValue<BigNumberish>;
    isActive: PromiseOrValue<boolean>;
  };

  export type TransferLimitStructOutput = [BigNumber, boolean] & {
    maxTransfers: BigNumber;
    isActive: boolean;
  };

  export type MemberLevelDependencyStruct = {
    minimumLevel: PromiseOrValue<BigNumberish>;
    isActive: PromiseOrValue<boolean>;
  };

  export type MemberLevelDependencyStructOutput = [number, boolean] & {
    minimumLevel: number;
    isActive: boolean;
  };

  export type ExpireableStruct = {
    expireTime: PromiseOrValue<BigNumberish>;
    isActive: PromiseOrValue<boolean>;
  };

  export type ExpireableStructOutput = [number, boolean] & {
    expireTime: number;
    isActive: boolean;
  };

  export type RoyaltyFeeStruct = {
    fee: PromiseOrValue<BigNumberish>;
    isActive: PromiseOrValue<boolean>;
  };

  export type RoyaltyFeeStructOutput = [number, boolean] & {
    fee: number;
    isActive: boolean;
  };

  export type ConstraintsStruct = {
    transferLimit: LibERC1155TransferConstraints.TransferLimitStruct;
    minimumMembershipLevel: LibERC1155TransferConstraints.MemberLevelDependencyStruct;
    expireable: LibERC1155TransferConstraints.ExpireableStruct;
    royaltyFee: LibERC1155TransferConstraints.RoyaltyFeeStruct;
  };

  export type ConstraintsStructOutput = [
    LibERC1155TransferConstraints.TransferLimitStructOutput,
    LibERC1155TransferConstraints.MemberLevelDependencyStructOutput,
    LibERC1155TransferConstraints.ExpireableStructOutput,
    LibERC1155TransferConstraints.RoyaltyFeeStructOutput
  ] & {
    transferLimit: LibERC1155TransferConstraints.TransferLimitStructOutput;
    minimumMembershipLevel: LibERC1155TransferConstraints.MemberLevelDependencyStructOutput;
    expireable: LibERC1155TransferConstraints.ExpireableStructOutput;
    royaltyFee: LibERC1155TransferConstraints.RoyaltyFeeStructOutput;
  };
}

export interface TicketCreateInterface extends utils.Interface {
  functions: {
    "expireable(uint256)": FunctionFragment;
    "ticketCreate(uint256,(string,string,string),((uint256,bool),(uint32,bool),(uint32,bool),(uint24,bool)))": FunctionFragment;
    "ticketCreateBatch(uint256[],(string,string,string)[],((uint256,bool),(uint32,bool),(uint32,bool),(uint24,bool))[])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "expireable" | "ticketCreate" | "ticketCreateBatch"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "expireable",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "ticketCreate",
    values: [
      PromiseOrValue<BigNumberish>,
      TicketCreate.TicketMetaStruct,
      LibERC1155TransferConstraints.ConstraintsStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "ticketCreateBatch",
    values: [
      PromiseOrValue<BigNumberish>[],
      TicketCreate.TicketMetaStruct[],
      LibERC1155TransferConstraints.ConstraintsStruct[]
    ]
  ): string;

  decodeFunctionResult(functionFragment: "expireable", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ticketCreate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ticketCreateBatch",
    data: BytesLike
  ): Result;

  events: {
    "MemberBanned(address,uint32)": EventFragment;
    "MemberLevelUpdated(tuple)": EventFragment;
    "MerkleRootUpdated(bytes32)": EventFragment;
    "MigrationCancelled(address,uint32)": EventFragment;
    "MigrationInitiated(address,uint32)": EventFragment;
    "OwnershipChanged(address,address)": EventFragment;
    "TicketsCreated(uint256,uint256,tuple)": EventFragment;
    "TransferBatch(address,address,address,uint256[],uint256[])": EventFragment;
    "TransferSingle(address,address,address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "MemberBanned"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MemberLevelUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MerkleRootUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MigrationCancelled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MigrationInitiated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TicketsCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TransferBatch"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TransferSingle"): EventFragment;
}

export interface MemberBannedEventObject {
  user: string;
  timestamp: number;
}
export type MemberBannedEvent = TypedEvent<
  [string, number],
  MemberBannedEventObject
>;

export type MemberBannedEventFilter = TypedEventFilter<MemberBannedEvent>;

export interface MemberLevelUpdatedEventObject {
  leaf: LibMemberLevel.LeafStructOutput;
}
export type MemberLevelUpdatedEvent = TypedEvent<
  [LibMemberLevel.LeafStructOutput],
  MemberLevelUpdatedEventObject
>;

export type MemberLevelUpdatedEventFilter =
  TypedEventFilter<MemberLevelUpdatedEvent>;

export interface MerkleRootUpdatedEventObject {
  newRoot: string;
}
export type MerkleRootUpdatedEvent = TypedEvent<
  [string],
  MerkleRootUpdatedEventObject
>;

export type MerkleRootUpdatedEventFilter =
  TypedEventFilter<MerkleRootUpdatedEvent>;

export interface MigrationCancelledEventObject {
  cancellor: string;
  timeCancelled: number;
}
export type MigrationCancelledEvent = TypedEvent<
  [string, number],
  MigrationCancelledEventObject
>;

export type MigrationCancelledEventFilter =
  TypedEventFilter<MigrationCancelledEvent>;

export interface MigrationInitiatedEventObject {
  initiatior: string;
  timeInitiatied: number;
}
export type MigrationInitiatedEvent = TypedEvent<
  [string, number],
  MigrationInitiatedEventObject
>;

export type MigrationInitiatedEventFilter =
  TypedEventFilter<MigrationInitiatedEvent>;

export interface OwnershipChangedEventObject {
  oldOwner: string;
  newOwner: string;
}
export type OwnershipChangedEvent = TypedEvent<
  [string, string],
  OwnershipChangedEventObject
>;

export type OwnershipChangedEventFilter =
  TypedEventFilter<OwnershipChangedEvent>;

export interface TicketsCreatedEventObject {
  arg0: BigNumber;
  arg1: BigNumber;
  arg2: TicketCreate.TicketMetaStructOutput;
}
export type TicketsCreatedEvent = TypedEvent<
  [BigNumber, BigNumber, TicketCreate.TicketMetaStructOutput],
  TicketsCreatedEventObject
>;

export type TicketsCreatedEventFilter = TypedEventFilter<TicketsCreatedEvent>;

export interface TransferBatchEventObject {
  operator: string;
  from: string;
  to: string;
  ids: BigNumber[];
  values: BigNumber[];
}
export type TransferBatchEvent = TypedEvent<
  [string, string, string, BigNumber[], BigNumber[]],
  TransferBatchEventObject
>;

export type TransferBatchEventFilter = TypedEventFilter<TransferBatchEvent>;

export interface TransferSingleEventObject {
  operator: string;
  from: string;
  to: string;
  id: BigNumber;
  value: BigNumber;
}
export type TransferSingleEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber],
  TransferSingleEventObject
>;

export type TransferSingleEventFilter = TypedEventFilter<TransferSingleEvent>;

export interface TicketCreate extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TicketCreateInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    expireable(
      ticketId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[void]>;

    ticketCreate(
      _amount: PromiseOrValue<BigNumberish>,
      _ticketMeta: TicketCreate.TicketMetaStruct,
      _constraints: LibERC1155TransferConstraints.ConstraintsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    ticketCreateBatch(
      _amount: PromiseOrValue<BigNumberish>[],
      _ticketMeta: TicketCreate.TicketMetaStruct[],
      _constraints: LibERC1155TransferConstraints.ConstraintsStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  expireable(
    ticketId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<void>;

  ticketCreate(
    _amount: PromiseOrValue<BigNumberish>,
    _ticketMeta: TicketCreate.TicketMetaStruct,
    _constraints: LibERC1155TransferConstraints.ConstraintsStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  ticketCreateBatch(
    _amount: PromiseOrValue<BigNumberish>[],
    _ticketMeta: TicketCreate.TicketMetaStruct[],
    _constraints: LibERC1155TransferConstraints.ConstraintsStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    expireable(
      ticketId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    ticketCreate(
      _amount: PromiseOrValue<BigNumberish>,
      _ticketMeta: TicketCreate.TicketMetaStruct,
      _constraints: LibERC1155TransferConstraints.ConstraintsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    ticketCreateBatch(
      _amount: PromiseOrValue<BigNumberish>[],
      _ticketMeta: TicketCreate.TicketMetaStruct[],
      _constraints: LibERC1155TransferConstraints.ConstraintsStruct[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "MemberBanned(address,uint32)"(
      user?: PromiseOrValue<string> | null,
      timestamp?: null
    ): MemberBannedEventFilter;
    MemberBanned(
      user?: PromiseOrValue<string> | null,
      timestamp?: null
    ): MemberBannedEventFilter;

    "MemberLevelUpdated(tuple)"(leaf?: null): MemberLevelUpdatedEventFilter;
    MemberLevelUpdated(leaf?: null): MemberLevelUpdatedEventFilter;

    "MerkleRootUpdated(bytes32)"(newRoot?: null): MerkleRootUpdatedEventFilter;
    MerkleRootUpdated(newRoot?: null): MerkleRootUpdatedEventFilter;

    "MigrationCancelled(address,uint32)"(
      cancellor?: null,
      timeCancelled?: null
    ): MigrationCancelledEventFilter;
    MigrationCancelled(
      cancellor?: null,
      timeCancelled?: null
    ): MigrationCancelledEventFilter;

    "MigrationInitiated(address,uint32)"(
      initiatior?: null,
      timeInitiatied?: null
    ): MigrationInitiatedEventFilter;
    MigrationInitiated(
      initiatior?: null,
      timeInitiatied?: null
    ): MigrationInitiatedEventFilter;

    "OwnershipChanged(address,address)"(
      oldOwner?: null,
      newOwner?: null
    ): OwnershipChangedEventFilter;
    OwnershipChanged(
      oldOwner?: null,
      newOwner?: null
    ): OwnershipChangedEventFilter;

    "TicketsCreated(uint256,uint256,tuple)"(
      arg0?: null,
      arg1?: null,
      arg2?: null
    ): TicketsCreatedEventFilter;
    TicketsCreated(
      arg0?: null,
      arg1?: null,
      arg2?: null
    ): TicketsCreatedEventFilter;

    "TransferBatch(address,address,address,uint256[],uint256[])"(
      operator?: PromiseOrValue<string> | null,
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      ids?: null,
      values?: null
    ): TransferBatchEventFilter;
    TransferBatch(
      operator?: PromiseOrValue<string> | null,
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      ids?: null,
      values?: null
    ): TransferBatchEventFilter;

    "TransferSingle(address,address,address,uint256,uint256)"(
      operator?: PromiseOrValue<string> | null,
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      id?: null,
      value?: null
    ): TransferSingleEventFilter;
    TransferSingle(
      operator?: PromiseOrValue<string> | null,
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      id?: null,
      value?: null
    ): TransferSingleEventFilter;
  };

  estimateGas: {
    expireable(
      ticketId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ticketCreate(
      _amount: PromiseOrValue<BigNumberish>,
      _ticketMeta: TicketCreate.TicketMetaStruct,
      _constraints: LibERC1155TransferConstraints.ConstraintsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    ticketCreateBatch(
      _amount: PromiseOrValue<BigNumberish>[],
      _ticketMeta: TicketCreate.TicketMetaStruct[],
      _constraints: LibERC1155TransferConstraints.ConstraintsStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    expireable(
      ticketId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ticketCreate(
      _amount: PromiseOrValue<BigNumberish>,
      _ticketMeta: TicketCreate.TicketMetaStruct,
      _constraints: LibERC1155TransferConstraints.ConstraintsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    ticketCreateBatch(
      _amount: PromiseOrValue<BigNumberish>[],
      _ticketMeta: TicketCreate.TicketMetaStruct[],
      _constraints: LibERC1155TransferConstraints.ConstraintsStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
