/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as diamondDeploySol from "./diamondDeploy.sol";
export type { diamondDeploySol };
export type { IDiamondDeploy } from "./IDiamondDeploy";
