/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Ecosystem } from "./Ecosystem";
export * as factories from "./factories";
export { Ecosystem__factory } from "./factories/Ecosystem__factory";
